//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.BUYTRANSACTIONs = new HashSet<BUYTRANSACTION>();
        }
    
        public int ItemNumber { get; set; }
        public int AuthorID { get; set; }
        public int YearPublished { get; set; }
        public string Keywords { get; set; }
        public int BookCondition { get; set; }
        public int PublisherID { get; set; }
        public string ISBN { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        public virtual BOOKCONDITION BOOKCONDITION1 { get; set; }
        public virtual ITEMDETAIL ITEMDETAIL { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYTRANSACTION> BUYTRANSACTIONs { get; set; }
    }
}
