//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUYTRANSACTION
    {
        public int BuyTransactionNumber { get; set; }
        public double TransactionAmount { get; set; }
        public double AmountPaid { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public int ItemNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual BOOK BOOK { get; set; }
    }
}
