//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMDETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEMDETAIL()
        {
            this.LENDTRANSACTIONs = new HashSet<LENDTRANSACTION>();
            this.RESERVATIONS = new HashSet<RESERVATION>();
        }
    
        public int ItemNumber { get; set; }
        public string Title { get; set; }
        public int CopiesOwned { get; set; }
        public int CopiesOnShelf { get; set; }
        public int CopiesBorrowed { get; set; }
        public int SubDivisionID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> ReservationID { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual CONFERENCEPROCEEDING CONFERENCEPROCEEDING { get; set; }
        public virtual DVD DVD { get; set; }
        public virtual ITEM ITEM { get; set; }
        public virtual SUBDIVISION SUBDIVISION { get; set; }
        public virtual JOURNAL JOURNAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LENDTRANSACTION> LENDTRANSACTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATION> RESERVATIONS { get; set; }
    }
}
