//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class LENDTRANSACTION
    {
        public int LendTransactionNumber { get; set; }
        public double TransactionAmount { get; set; }
        public System.DateTime DateBorrowed { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
        public System.DateTime DateDue { get; set; }
        public int ItemNumber { get; set; }
        public Nullable<System.DateTime> PaymentReceived { get; set; }
    
        public virtual ITEMDETAIL ITEMDETAIL { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
