//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LIBRARYEntities : DbContext
    {
        public LIBRARYEntities()
            : base("name=LIBRARYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHOR> AUTHORs { get; set; }
        public virtual DbSet<BOOK> BOOKs { get; set; }
        public virtual DbSet<BOOKCONDITION> BOOKCONDITIONs { get; set; }
        public virtual DbSet<BUYTRANSACTION> BUYTRANSACTIONs { get; set; }
        public virtual DbSet<CLASSIFICATION> CLASSIFICATIONs { get; set; }
        public virtual DbSet<CONFERENCEPROCEEDING> CONFERENCEPROCEEDINGS { get; set; }
        public virtual DbSet<DVD> DVDs { get; set; }
        public virtual DbSet<ITEM> ITEMs { get; set; }
        public virtual DbSet<ITEMDETAIL> ITEMDETAILs { get; set; }
        public virtual DbSet<JOURNAL> JOURNALs { get; set; }
        public virtual DbSet<LENDTRANSACTION> LENDTRANSACTIONs { get; set; }
        public virtual DbSet<LIBRARY> LIBRARies { get; set; }
        public virtual DbSet<MEMBERHISTORY> MEMBERHISTORies { get; set; }
        public virtual DbSet<PUBLISHER> PUBLISHERs { get; set; }
        public virtual DbSet<RESERVATION> RESERVATIONS { get; set; }
        public virtual DbSet<SUBDIVISION> SUBDIVISIONs { get; set; }
        public virtual DbSet<SUBJECT> SUBJECTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
