//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBER()
        {
            this.MEMBERHISTORies = new HashSet<MEMBERHISTORY>();
            this.LENDTRANSACTIONs = new HashSet<LENDTRANSACTION>();
        }
    
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int ClasssificationID { get; set; }
        public string Email { get; set; }
        public Nullable<double> TotalOverdueCharge { get; set; }
        public Nullable<System.DateTime> MemberIDRenewal { get; set; }
        public int LibraryID { get; set; }
    
        public virtual CLASSIFICATION CLASSIFICATION { get; set; }
        public virtual LIBRARY LIBRARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBERHISTORY> MEMBERHISTORies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LENDTRANSACTION> LENDTRANSACTIONs { get; set; }
    }
}
