//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERHISTORY
    {
        public int HistoryID { get; set; }
        public System.DateTime DateBorrowed { get; set; }
        public System.DateTime DateDue { get; set; }
        public System.DateTime DateReturned { get; set; }
        public Nullable<double> AmountCharged { get; set; }
        public int MemberID { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
    }
}
