//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public int ReservationID { get; set; }
        public int ItemNumber { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public int MemberID { get; set; }
    
        public virtual ITEMDETAIL ITEMDETAIL { get; set; }
    }
}
